name: Automatically Build image on tag ONLY
on:
    push:
        tags: [ '*' ]

jobs:
    build:
        runs-on: ubuntu-18.04
        steps:
        - uses: actions/checkout@v1
        - name: Run Apt-get update
          run: sudo apt-get update
        - name: Install Dependencies
          run: sudo apt-get -y install quilt qemu-user-static debootstrap bsdtar
        - name: Run Build script
          run: sudo ./build.sh
        - name: Copy ZIP to current working dir
          run: cp deploy/*.zip ./
        - name: Debug current working dir
          run: ls -la
        - name: Release Image to placeholder or release
          uses: meeDamian/github-release@v1.0.0
          if: startsWith(github.ref, 'refs/tags/')
          with:
            gzip: false
            files: "*.zip"
            token: ${{ secrets.GITHUB_TOKEN }}
            allow_override: true
